title: My New Blog
author: xioumau
email: mauriciocon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to make a nice blog on GitHub Pages.

# social links
twitter_username: xioumau # DO NOT include the @ character, or else the build will fail!
github_username:  xioumau # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
